config/routes.rb
Myfavplaces::Application.routes.draw do
  root :to => "lists#index"
  
  resources :lists do
    resources :places
  end

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  
  get '/preferences' => "lists#preferences"
  get '/places/:id/modal' => "places#modal"
  post '/addplace' => "places#add_rec"
  post '/blacklist' => "places#blacklist"
  delete '/blacklist/:placeid' => "places#remove_from_blacklist"
  get '/discover' => "pages#discover"

end

app/models/list.rb
class List < ActiveRecord::Base
  # attr_accessible :name, :user_id

  # belongs_to :user
  belongs_to :map
  has_many :list_places
  has_many :places, :through => :list_places
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]

  # GET /lists
  # GET /lists.json
  def index
    if user_signed_in?
      # current_user.get_coordinates
      # coordinates = Geocoder.coordinates("#{current_user.city}, #{current_user.state}") || [40.739453,-73.973613]
      # current_user.lat = coordinates[0]
      # current_user.long = coordinates[1]
      # current_user.save
      User.get_users(current_user)
      @joyride = current_user.joyride
      @recommendations = current_user.recommend
      #  LEFT OFF HERE, CURRENTMAP IS NOT PERSISTING
      @current_map = current_user.currentmap
      @blacklist = current_user.blacklists.map {|b| b.place}
      @lists = @current_map.lists.reverse
      if @lists.length == 0
        List.create(name: "Casual bites", map_id: @current_map.id)
        List.create(name: "Brunch favs", map_id: @current_map.id)
        List.create(name: "Bar scene", map_id: @current_map.id)
        @lists = @current_map.lists.reverse
      end
      debugger
      @places = @lists.map {|list| list.places}
      gon.long = current_user.lat.to_f 
      gon.lat = current_user.long.to_f
      gon.lists = current_user.lists
      gon.places_hash = {}
      gon.lists.each do |list|
        gon.places_hash[list.name] = list.places
      end
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lists }
    end
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @list = List.find(params[:id])
    @places = @list.places

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/new
  # GET /lists/new.json
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
    
    @list = List.find(params[:id])
    
    if current_user.id != @list.user_id
     flash[:notice] = "Sorry, you cannot edit this list."
     redirect_to(lists_path)
    end
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(params[:list])

    if user_signed_in? 
      @list.map_id = current_user.default_map
    end

    respond_to do |format|
      if @list.save
        format.js
        format.html { redirect_to "/"} # , notice: 'List was successfully created.' 
        format.json { render json: @list, status: :created, location: @list }
      else
        format.html { render action: "new" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lists/1
  # PUT /lists/1.json
  def update
    @list = List.find(params[:id])

    respond_to do |format|
      if @list.update_attributes(params[:list])
        format.js {@list}
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list_id = params[:id]
    @list = List.find(params[:id])
    @list.destroy
    @list.places.each {|place| place.destroy }
    respond_to do |format|
      # format.js
      format.html { redirect_to lists_url }
      format.json { head :no_content }
    end
  end

  def preferences
    # @recommendations = current_user.recommend
    @blacklist = current_user.blacklists.where("subtype = 'black'")
    @blacklist = @blacklist.map {|b|  Place.find_by_placeid(b.place) }
    @graylist = current_user.blacklists.where("subtype = 'gray'")
    @graylist = @graylist.map {|b|  Place.find_by_placeid(b.place) }
    
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_buttons.html.erb
<!-- DELETE LIST-->
<%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, '#', :class => 'pull-right', id: "delete_list_#{list.id}" %>

<!-- EDIT LIST -->
<%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_list_path(list), :class => 'pull-right edit_link', id: "edit_list_#{list.id}", remote: true %>

<!-- ADD PLACE -->
<%= link_to '<i class="fa fa-plus"></i>'.html_safe, new_list_place_path(:list_id => list.id), :class => 'pull-right new_placelink', id: "new_placelink_#{list.id}" %>

<%#= link_to '<i class="fa fa-plus"></i>'.html_safe, new_list_place_path(:list_id => list.id), :class => 'pull-right new_placelink', id: 'new_placelink', remote: true %>

<!-- AJAX -->
<script type="text/javascript">
  $('#delete_list_<%= list.id %>').click(function(e) {
    e.preventDefault();
    var answer = confirm ("Are you sure you want to this list and all of its places?");
    var that = $(this);
    if (answer) {
      $.ajax({
        type: "delete", // method
        url: "/lists/" + <%= list.id %>,
        type: "post",
        dataType: "json",
        data: {"_method":"delete"},
        success: function(response){
          that.parent().parent().fadeOut(500);
        }
      })
    }
  });
</script>

app/views/lists/_form.html.erb
<%= form_for @list, remote: true do |f| %>
  
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="large-12 columns">
      <div class="row collapse">
        <div class="small-9 columns">
          <%= f.text_field :name, :placeholder => "Name a new list" %>
        </div>
        <div class="small-3 columns">
          <%= f.submit :ADD, :class=> "button postfix" %>
        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/lists/_intro_joyride.html.erb
<!-- At the bottom of your page but inside of the body tag -->
<ol class="joyride-list" data-joyride>
  <li data-button="Okay" data-text="Next" data-options="tip_location: top">
    <h4>Welcome to Localist!</h4>
    <p>Let me show you around real quick.</p>
  </li>
  <li data-id="intro1" data-class="custom so-awesome" data-text="Next" class="recommendation_tip">
    <h4>Recommendations</h4>
    <p>This is where you'll find recommendations. We personalize them based on your places, so you'll need to add some first.</p>
  </li>
  <li data-id="intro2" data-button="Next" data-options="tip_location:bottom;tip_animation:fade">
    <h4>Make Lists</h4>
    <p>This is where you create and manage your lists. Make as many as you want!</p>
  </li>

  <li data-id="intro3" data-button="Next" data-options="tip_location:bottom;tip_animation:fade" class="addplaces_tip">
    <h4>Add Places</h4>
    <p>Adding places to lists is easy. Just click on this button to search for a place on the map.</p>
  </li>

  <li data-id="intro4" data-button="Next" data-options="tip_location:bottom;tipAdjustmentX:250;nub_position:left;tip_animation:fade" class="filters_tip">
    <h4>Filters</h4>
    <p>Toggle which lists you want to see on the map.</p>
  </li>


  <li data-button="End">
    <h4>Your turn</h4>
    <p>Have fun making lists and discovering places!</p>
  </li>
</ol>

app/views/lists/_list.html.erb
<div class="listcontainer" id="list_container_<%= list.id %>">
  <div class="list-title">

    <%= link_to list.name, "#panel#{list.id}", :class =>'list_name', id: "list_#{list.id}" %>   
    <%= render 'buttons', :list => list %>
  </div>
  <div class="placecontainer"  >
    <ul class="places" id="panel<%= list.id%>">
      <% if list.places.length == 0 %> 
        <li class="place" id="intro3"> 
          <%= link_to 'Click to add a place', "new_list_place_path(:list_id => list.id)", id: "new_placefor_#{list.id}", :class => "new_placelink" %>
        </li>   
      <% else %> 
        <% list.places.each do |place|  %>
        <li class="place" > 
          <a href="/places/<%= place.id %>/modal" data-reveal-id="show_<%= place.id %>" data-reveal-ajax="true" class="show_place" data-place="<%= place.id %> "> <%= place.name %> </a>
          <!-- DELETE -->
          <%= link_to '<i class="fa fa-trash-o"></i>'.html_safe,  list_place_path(:list_id => list.id, :id => place.id), method: :delete, :class => 'pull-right', id: "delete_place_#{place.id}", remote: true  %>
        </li>
      
        <!-- AJAX for block -->
          <script type="text/javascript">
            // DELETE PLACE
            $('#delete_place_<%= place.id %>').click(function(e) {
              e.preventDefault();
              var answer = confirm ("Are you sure you want to this place?");
              var that = $(this);
              if (answer) {
                $.ajax({
                  type: "delete", // method
                  url: "/lists/" + <%= list.id %> + "/places/" + <%= place.id %>,
                  type: "post",
                  dataType: "json",
                  data: {"_method":"delete"},
                  success: function(response){  
                    that.parent().fadeOut(500);
                  }
                })
              }
            });

            // SHOW ACTIONS ON HOVER
            $('.pull-right').hide();
            $('.place, .list-title').on({
              'mouseenter': function(){
                $(this).find('.pull-right').show();
              },
              'mouseleave' : function(){
                $(this).find('.pull-right').hide();  
              }
            });
          </script>
          <% end %> 
        <% end %>  
    </ul>
  </div>
</div>

      

app/views/lists/_recommendations.html.erb
<h3 class="inline-block" > Recommendations for you </h3> 
<a href="/preferences" class="tiny" id="prefs"><i class="fa fa-cog"></i></a>
<p class="tiny" id="hiderecs">Hide</p>

<div class="recommendations" id="intro1" >  
  <% if @recommendations.length == 0 %>
      <div class="alert-message"> No recommendations yet. <br>Add some more places, and check back later!</div>
    <% else %> 
  <ul>
    <% @recommendations.each do |basis, lists_hash|  %>
      <% lists_hash.each do |list, recs| %>
        <!-- random sampling of 5 recs per place  -->       
        <% recs.shuffle.sample(5).each do |place| %> 
          <% if @blacklist.include?(place.placeid) %>
            <% next %>
          <% else %>
            <li class="rec-container">
              <div class="square-container">
                <% if place.photos.length > 0 %>
                  <img src=<%= place.photos[0].url %> class="rec"> 
                <% else %>
                  <%= image_tag "/images/placeholder.png", class: "rec" %>
                <% end %>
                <div class="hover-actions">
                  <div class="white icon" data-reveal-id="remove_<%= place.id %>" data-place="<%= place.id %> "> x </div>
                  <div class="button-group">
                    <a href="/places/<%= place.id %>/modal" data-reveal-id="show_<%= place.id %>" class="button tiny outline-button block show_place" data-reveal-ajax="true" data-place="<%= place.id %> "> View details </a>
                    <a href="#" class="button tiny outline-button block" data-reveal-id="add_<%= place.id %>" data-place="<%= place.id %> " > Add to list </a>
                  </div>
                </div>
              </div>
              <p class="rec-title center"><%= place.name %> </p>
              <p class="rec-detail center">(based on <%= basis %>)</p>
            </li> 
          <% end %>

          
          <!-- THIS MODAL SHOWS WHEN U CLICK 'SHOW DETAILS' -->
          <div id="show_<%= place.id %>" class="reveal-modal medium" data-reveal>
            <h3><%= place.name %></h3>
            <div class="row">
              <div class="large-12 columns">
                <% if place.photos.length > 0 %> <% photos = place.photos.map {|photo| photo.url } %>
                  <div class="largephoto-container img scrubber">
                    <img src=<%= place.photos[0].url %> class="large">
                    <div class="photoarray" data-photos= "<%=photos %>">  </div>
                    <div class="details">
                      <div class="wrap">
                      <!-- name of the place -->
                      <a class="artist" href="#"></a> 
                      <%= "#{place.photos.length} photos" %>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
            <a class="close-reveal-modal">&#215;</a>
          </div> 


          <!-- THIS MODAL SHOWS WHEN U CLICK ADD TO LIST -->
          <div id="add_<%= place.id %>" class="reveal-modal tiny" data-reveal>
            <form action="/addplace" method="post" class="new_place" id="new_place">
              <h3>Add '<%= place.name %>' to:</h3>
              <div class="row">
                <div class="large-12 columns">
                    <input type="hidden" name="place" value="<%= place.id %>">
                    <select name="list">
                      <% @lists.each do |list| %>
                        <option value="<%=list.id %>" name="list"> <%= list.name %></option>
                      <% end %>
                    </select>
                    <div class=actions>
                      <button type="submit" name="commit" id="place-submit-button" value="Add Place">Add</button>
                    </div>
                </div>
              </div>
            </form>
            <a class="close-reveal-modal">&#215;</a>
          </div> 

          <!-- THIS MODAL SHOWS WHEN U CLICK THE 'X' -->
          <div id="remove_<%= place.id %>" class="reveal-modal tiny" data-reveal>
            <form action="/blacklist" method="post" >
                <h3>What should I do with <%=place.name%>? </h3>
                <div class="row">
                  <div class="large-12 columns">
                      <input type="hidden" name="blacklist[place]" value="<%= place.placeid %>">
                      <input type="hidden" name="blacklist[user_id]" value="<%= current_user.id %>">
                      <div class=actions>
                        <button type="submit" name="blacklist[subtype]" value="black">Don't recommend it again</button>
                        <button type="submit" name="blacklist[subtype]" value="gray">I'm not interested right now</button>
                      </div>
                  </div>
                </div>
              </form>
            <a class="close-reveal-modal">&#215;</a>
          </div> 

      <% end %>  
    <% end %>
  <% end %>
  
  </ul>
  <% end %>
</div>  

app/views/lists/_welcome.html.erb
<div id="splash">
  <div id="splash-cover">
    <h1 id="main" class="white">LOCALIST</h1>
    <ul id="taglines">
      <li class="hidden"><h2 id="tagline" class="white"> Curate your favorite local spots </h2></li>
      <li class="hidden"><h2 id="tagline" class="white"> Get personalized recommendations </h2></li>
      <li class="hidden"><h2 id="tagline" class="white"> Discover hidden gems </h2></li>
    </ul>
      <div class="center flip">
        <div class="card">
          <div class="center signin-container form">
            <%= render 'devise/sessions/new' %>
          </div>

          <div class="center signup-container form">
            <%= render 'devise/registrations/new' %>
          </div>
        </div>
      </div>
   
  </div>  
</div>

<!-- FLIP EFFECT -->
<script type="text/javascript">
  $('#signup').click(function(e){
    e.preventDefault(); 
    $('.flip').find('.card').addClass('flipped').mouseleave(function(){
      $('.flip').removeClass('flipped');
    });
    return false;
  });

  $('#signin').click(function(e){
    e.preventDefault(); 
    $('.flip').find('.card').removeClass('flipped').mouseleave(function(){
    $('.flip').addClass('flipped');
  });
  return false;
});

</script>

app/views/lists/create.js.erb
$('#new_list').remove();
$('#new_link').show();
$('.lists').prepend('<%= j render(@list) %>')

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/edit.js.erb
$('#list_<%= @list.id %>').hide().after('<%= j render("form") %>');

app/views/lists/index.html.erb
<% if user_signed_in? %>
  <div class="container" >
    
    <%= render 'recommendations' %>
  
    <!-- STICKY NAV OF FILTERS -->
    <!-- <div data-magellan-expedition="fixed" class="stickynav"> -->
        <div id="filters">
          <h3 class="inline-block"> LISTS </h3>  <p class="tiny selected margin-after" id="view">Hide</p>
            <ul class="filters inline-block" id="intro4">
              
              <li class="selected">All</li>
                <% @lists.each do |list| %>
                  <li class="selected"><%= list.name %></li>
                <% end %>
            </ul>
        </div> 
    <!-- </div> -->
  </div>
  
  <!-- SIDENAV -->
  <div class="listview">
    <div id="hidden-form"></div>
    
    <div class="sidenav" >
      <!-- <p> -->
        <%= link_to 'Create New List',new_list_path, id: 'new_link', remote: true, class: "button button-special"  %> 
      <!-- </p> -->
      <!-- <p class="tiny toggle_lists collapse">Collapse All</p>   -->
      <div class="lists" id="intro2">

        <%= render @lists %>
      </div>
    </div>
  </div>

  <!-- INFOWINDOW -->
    <div class="hidden">
    <% @lists.each do |list| %>
      <% list.places.each do |place| %>
        <div id="tooltip_<%= place.id %>" class="infowindow">
          <!-- <div class="pull-left">  -->
            <p class="listing-title-map"><%= place.name %> <br>
             <span class="small"> <%= ("$"* place.price_level.to_i) %> | <%= ("\u2605"* place.rating.to_i) %> | <%= link_to 'Website', place.website %> </span>
            </p>
            <% if place.photos.length > 0 %>
              <div class="thumb-container">
                <img src=<%= place.photos[0].url %> class="thumb">
              </div>
            <% end %>
            <div class="listing-detail">
              <!-- <p> <%#= place.rating %> stars</p> -->
             <!--  <p class="tiny"> <%#= place.address %> </p>
              <p class="tiny"><i class="fa fa-phone"></i> &nbsp <%#= place.phone %> </p>
              <a href=<%#= place.website%> target="_blank"><p class="tiny"> <i class="fa fa-external-link"></i> <%#= place.website %> </p></a> -->
            </div>
        </div>
        
        <!-- SHOW PLACE MODAL -->
        <div id="show_<%= place.id %>" class="reveal-modal medium" data-reveal>
          <h3><%= place.name %></h3>
          <div class="row">
            <div class="large-12 columns">
              <% if place.photos.length > 0 %> <% photos = place.photos.map {|photo| photo.url } %>
                <div class="largephoto-container img scrubber">
                  <img src=<%= place.photos[0].url %> class="large">
                  <div class="photoarray" data-photos= "<%=photos %>">  </div>
                  <div class="details">
                    <div class="wrap">
                    <!-- name of the place -->
                    <a class="artist" href="#"></a> 
                    <%= "#{place.photos.length} photos" %>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
          <a class="close-reveal-modal">&#215;</a>
        </div> 
      <% end %>
    <% end %>
  </div>

  <div id="map-canvas" ></div>
    
  <%= javascript_include_tag "map" %>

  <% if @joyride %>
    <%= render 'intro_joyride' %>
  <% end %> 

<% else %>
  <%= render 'welcome' %>
<% end %>

app/views/lists/new.html.erb
<h1>New list</h1>
<%= render 'form' %>

app/views/lists/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>');

app/views/lists/preferences.html.erb
<div class="container">

  <h2 class="subheading"> Recommendation Preferences</h2><br>

<!--
  <h3 class="inline-block hideblock">Preferences</h3> <p class="tiny" >Hide</p>
  <div class="recommendations">  
  </div> 
-->

  <!-- <h3 class="inline-block">Recommendations</h3>  -->
  <!-- <p class="tiny hideblock" >Hide</p> -->
  <div class="preferences">  
      <div id="filters">
        <h3 class="inline-block"> Price Level: </h3>  
          <ul class="filters price inline-block" >
            <li class="selected">All</li>
            <li class="selected">$</li>
            <li class="selected">$$</li>
            <li class="selected">$$$</li>
            <li class="selected">$$$$</li>
          </ul>
        <br><br>
        <h3 class="inline-block"> Rating: </h3>  
          <ul class="filters rating inline-block" style="margin-left: 50px;" >
            
            <li class="selected">All</li>
            <li class="selected">&#x2605;</li>
            <li class="selected">&#x2605;&#x2605;</li>
            <li class="selected">&#x2605;&#x2605;&#x2605;</li>
            <li class="selected">&#x2605;&#x2605;&#x2605;&#x2605;</li>
            <li class="selected">&#x2605;&#x2605;&#x2605;&#x2605;&#x2605;</li>
          </ul>
      </div> 
      <br><br>
      <div>
      <ul class="pricing-table columns large-6">
        <li class="heading bullet-item">Never recommend</li>
        <% if @blacklist.length == 0 %>
            <br> <p class="center">You don't have any places. </p>
        <% else %>
        <% @blacklist.each do |place| %>
          <li class="bullet-item"> 
            <a href="/places/<%= place.id %>/modal" data-reveal-id="show_<%= place.id %>" data-reveal-ajax="true" data-place="<%= place.id %> "> <%= place.name %></a> 
            <div class="icon-inline inline-block" id= "delete_blacklist_<%=place.placeid%>" > x </div>
          </li>
          <div id="show_<%= place.id %>" class="reveal-modal medium" data-reveal></div>
        
           <!-- AJAX -->
          <script type="text/javascript">
            $('#delete_blacklist_<%=place.placeid%>').on('click', function(e) {
              e.preventDefault();
              var answer = confirm ("Are you sure you want to remove this place from your blacklist?");
              var that = $(this);
              if (answer) {
                $.ajax({
                  type: "delete", // method
                  url: "/blacklist/<%= place.placeid %>",
                  dataType: "html",
                  data: {"_method":"delete"}
                }).success(function(){
                    that.parent().fadeOut(500);
                })
              }
            });
          </script>
        <% end %>
        <% end %>
      </ul>

      <ul class="pricing-table columns large-6">
        <li class="heading bullet-item">Not interested right now</li>
        <% if @graylist.length == 0 %>
            <br> <p class="center">You don't have any places. </p>
        <% else %>
        <% @graylist.each do |place| %>
          <li class="bullet-item"> 
            <a href="/places/<%= place.id %>/modal" data-reveal-id="show_<%= place.id %>" data-reveal-ajax="true" data-place="<%= place.id %> "> <%= place.name %></a> 
            <div class="icon-inline inline-block" id= "delete_blacklist_<%=place.placeid%>" > x </div>
          </li>
          <div id="show_<%= place.id %>" class="reveal-modal medium" data-reveal></div>
        
           <!-- AJAX -->
          <script type="text/javascript">
            $('#delete_blacklist_<%=place.placeid%>').on('click', function(e) {
              e.preventDefault();
              var answer = confirm ("Are you sure you want to remove this place from your blacklist?");
              var that = $(this);
              if (answer) {
                $.ajax({
                  type: "delete", // method
                  url: "/blacklist/<%= place.placeid %>",
                  dataType: "html",
                  data: {"_method":"delete"}
                }).success(function(){
                    that.parent().fadeOut(500);
                })
              }
            });
          </script>

        <% end %>
        <% end %>
      </ul>
      </div>
      <a href="/" class="button save">Save </a>  
      <a href="/" class="pull-left back">Back </a>  
  </div>
        
      
</div>

<!-- STILL NEED TO ADD JQUERY SCROLL FUNCTION TO THIS MODAL, NOT BEING SELECTED -->
<script type="text/javascript">
  $(document).ready(function(){
    
    // Toggle preference sections
    $('.hideblock').on('click', function(){
      if ($(this).html() == "Hide") {
        $(this).html("Show")
        $(this).next().slideToggle();
      } else {
        $(this).html("Hide")
      }
    })

    // Toggle 'all' to control other selectors
    $(".price li").first().on('click',function(){
      $(this).toggleClass("");
      if($(this).hasClass("selected")){
        $(this).nextAll().removeClass("selected");
      } else {
        $(this).nextAll().addClass("selected");
      }
    })

    $(".rating li").first().on('click',function(){
      $(this).toggleClass("");
      if($(this).hasClass("selected")){
        $(this).nextAll().removeClass("selected");
      } else {
        $(this).nextAll().addClass("selected");
      }
    })

    // Toggle 'selected' class for each filter
    $(".price li, .rating li").on('click',function(){
      $(this).toggleClass("selected");
    })

  })
</script>

app/views/lists/update.js.erb
$('form').hide();
$('#list_<%= @list.id %>').show();