config/routes.rb
Myfavplaces::Application.routes.draw do
  root :to => "lists#index"
  
  resources :lists do
    resources :places
  end

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  
  get '/preferences' => "lists#preferences"
  get '/places/:id/modal' => "places#modal"
  post '/addplace' => "places#add_rec"
  post '/blacklist' => "places#blacklist"
  delete '/blacklist/:placeid' => "places#remove_from_blacklist"
  get '/discover' => "pages#discover"

end

app/views/layouts/_footer.html.erb
<footer>

</footer>

app/views/layouts/_header.html.erb
<nav>
  <div class="center">
    <h1 class="logo" ><%= link_to "The Localist", :root %> </h1>
    <ul class="nav">
    <% if user_signed_in? %>
      <li> <%= link_to 'DISCOVER', discover_path %></li>
      <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
    <% else %>
      <li><%= link_to 'Sign in', new_user_session_path %></li>  
    <% end %>
    </ul>
  </div>

  <div class="pull-right">
    
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>localist</title>
    <%= include_gon %>
    <link href='http://fonts.googleapis.com/css?family=Alegreya+Sans+SC:100,300,400,700,800|Jura:400,300|Glegoo|PT+Serif+Caption|Open+Sans:400,300,600,700,800|Roboto+Slab' rel='stylesheet' type='text/css'>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"></script>
    <script type="text/javascript" src="http://google-maps-utility-library-v3.googlecode.com/svn/trunk/infobox/src/infobox.js"></script>
    <%= javascript_include_tag "application" %>


    <%= csrf_meta_tags %>
  </head>
  <body>
    <% if user_signed_in? %>
      <%= render 'layouts/header' %>
    <% end %>
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
    <% end %>
    <%= yield %>

    
    <% if user_signed_in? %>
      <%= render 'layouts/footer' %>
    <% end %>
    <script>
      $(document).foundation();
    </script>

  </body>
</html>